"""Bridge one generated NPZ robustness case to the canonical E2V3 trainer.

Use this adapter for robustness data generated by ``NC/Data_generation``.  It
converts the time-major delivery array to the raw PyG layout, then launches
the unchanged ``NC/SIGN-phase/trainer.py`` with the matching E2V3 flags.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import subprocess
import sys

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
CANONICAL = ROOT / "SIGN-phase"
sys.path.insert(0, str(ROOT))

from Data_generation.prepare_npz_for_e2v3 import convert


SYSTEM_NAMES = {
    "kuramoto": "Kuramoto",
    "sis": "SIS",
    "gene": "Gene",
    "michaelis_menten": "MM",
    "mutual": "Mutual",
    "mutualistic": "Mutual",
    "fhn": "FHN",
    "hr": "HR",
    "rossler": "Rossler",
    "chua": "Chua",
}


def read_shape(source: Path) -> tuple[str, int, int, int, float]:
    with np.load(source, allow_pickle=True) as raw:
        x = np.asarray(raw["x"])
        if x.ndim != 3:
            raise ValueError("source x must have shape [time,node,dimension]")
        t = np.asarray(raw["t"], dtype=np.float64).reshape(-1)
        if len(t) != x.shape[0] or len(t) < 2:
            raise ValueError("source t does not align with x")
        system_raw = raw["system"].item() if "system" in raw else ""
        system = SYSTEM_NAMES.get(str(system_raw).lower(), str(system_raw))
        dt = float(np.median(np.diff(t)))
    return system, int(x.shape[1]), int(x.shape[2]), int(x.shape[0]), dt


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--source", required=True, type=Path)
    p.add_argument("--data-root", required=True, type=Path, help="Parent directory for the canonical E2V3 dataset root")
    p.add_argument("--edge-key", choices=["edge_index", "supplied_edge_index"], default="supplied_edge_index")
    p.add_argument("--phase", choices=["e1", "e2"], default="e1")
    p.add_argument("--system", default="", help="Canonical name; inferred from NPZ when omitted")
    p.add_argument("--network", default="from_file")
    p.add_argument("--library", choices=["L1", "L2", "L3"], default="L2")
    p.add_argument("--basis-variant", choices=["legacy", "trig", "trig_exp_v2"], default="trig_exp_v2")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--e1-output-root", type=Path, default=Path("output/e1"))
    p.add_argument("--e2-input-root", type=Path, default=Path("output/e1"))
    p.add_argument("--e2-output-root", type=Path, default=Path("output/e2"))
    p.add_argument("--python-bin", default=sys.executable)
    p.add_argument("--device", choices=["cpu", "cuda"], default="cpu")
    p.add_argument("--epochs", type=int, default=300)
    p.add_argument("--teacher", type=int, default=5)
    args = p.parse_args()

    source = args.source.expanduser().resolve()
    system, nodes, dims, steps, dt = read_shape(source)
    system = args.system or system
    if system not in set(SYSTEM_NAMES.values()):
        raise ValueError(f"Cannot map source system to canonical E2V3 name: {system}")
    data_root = args.data_root.expanduser().resolve()
    dataset_root = data_root / f"{system}_{nodes}_{args.network}_{dt}_{steps}"
    convert(source, dataset_root, edge_key=args.edge_key, observed=True)

    e1_output = args.e1_output_root.expanduser().resolve()
    e2_input = args.e2_input_root.expanduser().resolve()
    e2_output = args.e2_output_root.expanduser().resolve()
    command = [
        args.python_bin, str(CANONICAL / "trainer.py"),
        "--ode_model", system,
        "--network", args.network,
        "--num_atoms", str(nodes),
        "--dims", str(dims),
        "--time_stamp", str(steps),
        "--time_interval", str(dt),
        "--data_root", str(data_root),
        "--no-generate_data_if_missing",
        "--e1_library", args.library,
        "--e1_basis_variant", args.basis_variant,
        "--seed", str(args.seed),
        "--dataset_seed", "0",
        "--batch_size", "1",
        "--teacher", str(args.teacher),
        "--epochs", str(args.epochs),
        "--lr", "0.005",
        "--e1_intercept_mode", "with" if system in {"FHN", "SST"} else "aic",
        "--e1_intercept_aic_margin", "5.0",
        "--e1_ard_threshold_lambda", "1e4",
        "--e1_ard_max_iter", "2000",
        "--e1_lasso_alpha", "0.005",
        "--e1_lasso_max_iter", "2000",
        "--e1_dbscan_coef_relative_threshold", "0",
        "--e1_final_coef_relative_threshold", "0",
        "--e1_max_selected_terms", "0",
        "--lasso_node_num", "50",
        "--lasso_neighbor_num", "200",
        "--e1_output_root", str(e1_output),
    ]
    if args.device == "cpu":
        command.append("--no_cuda")
    if args.phase == "e1":
        command.extend(["--e1_condition", "clean", "--e1_mask_only"])
    else:
        command.extend([
            "--e1_condition", "clean",
            "--e2_from_e1_mask",
            "--e2_input_root", str(e2_input),
            "--e2_output_root", str(e2_output),
            "--e2_sparse_warmup_epochs", "30",
            "--e2_min_epochs", "30",
            "--e2_loss_patience", "30",
            "--e2_support_patience", "40",
            "--e2_abs_loss_stop", "1e-8",
            "--e2_abs_loss_min_epochs", "8",
            "--e2_normalize_sparsity_loss",
            "--e2_reset_optimizer_after_warmup",
            "--e2_post_warmup_lr", "0.001",
        ])
    print(json.dumps({"canonical_command": command, "dataset_root": str(dataset_root)}, indent=2, ensure_ascii=False))
    completed = subprocess.run(command, cwd=CANONICAL)
    return int(completed.returncode)


if __name__ == "__main__":
    raise SystemExit(main())
